# PDF Report Generator for InsightRural
# Generates downloadable college recommendation reports

from fpdf import FPDF
from datetime import datetime
import os


class CollegeReportPDF(FPDF):
    """Custom PDF class for InsightRural reports."""
    
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        
    def header(self):
        # Logo/Brand
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(16, 163, 127)  # Primary green
        self.cell(0, 10, 'InsightRural', align='C', ln=True)
        
        self.set_font('Helvetica', '', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, 'AI-Powered Educational Guidance for Rural Students', align='C', ln=True)
        
        # Line separator
        self.ln(5)
        self.set_draw_color(16, 163, 127)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(10)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by InsightRural AI | Page {self.page_no()}', align='C')
        
    def add_section_title(self, title, emoji=""):
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(30, 144, 255)  # Blue
        self.cell(0, 10, f'{emoji} {title}', ln=True)
        self.ln(2)
        
    def add_subsection(self, title):
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(60, 60, 60)
        self.cell(0, 8, title, ln=True)
        
    def add_text(self, text, bold=False):
        self.set_font('Helvetica', 'B' if bold else '', 10)
        self.set_text_color(0, 0, 0)
        self.multi_cell(0, 6, text)
        self.ln(2)
        
    def add_key_value(self, key, value, key_width=50):
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(60, 60, 60)
        self.cell(key_width, 6, f'{key}:', align='L')
        
        self.set_font('Helvetica', '', 10)
        self.set_text_color(0, 0, 0)
        self.cell(0, 6, str(value), ln=True)


def generate_college_report(prediction_result: dict, student_profile: dict) -> bytes:
    """
    Generate a PDF report from college prediction results.
    
    Args:
        prediction_result: Result from ML predictor
        student_profile: Student's profile data
        
    Returns:
        PDF content as bytes
    """
    pdf = CollegeReportPDF()
    pdf.add_page()
    
    # Report Title
    pdf.set_font('Helvetica', 'B', 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 15, 'KCET College Prediction Report', align='C', ln=True)
    
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, f'Generated on: {datetime.now().strftime("%d %B %Y, %I:%M %p")}', align='C', ln=True)
    pdf.ln(10)
    
    # ===== STUDENT PROFILE SECTION =====
    pdf.add_section_title('Student Profile', '')
    
    profile_box_y = pdf.get_y()
    pdf.set_fill_color(240, 248, 255)  # Light blue background
    pdf.rect(10, profile_box_y, 190, 35, 'F')
    
    pdf.set_xy(15, profile_box_y + 5)
    pdf.add_key_value('KCET Rank', student_profile.get('kcet_rank', 'N/A'))
    pdf.set_x(15)
    pdf.add_key_value('Category', student_profile.get('category', 'N/A'))
    pdf.set_x(15)
    pdf.add_key_value('Preferred Branches', ', '.join(student_profile.get('preferred_branches', [])))
    
    if student_profile.get('preferred_locations'):
        pdf.set_x(15)
        pdf.add_key_value('Preferred Locations', ', '.join(student_profile.get('preferred_locations', [])))
    
    pdf.ln(10)
    
    # ===== PREDICTION SUMMARY =====
    pdf.add_section_title('Prediction Summary', '')
    
    predictions = prediction_result.get('predictions', [])
    total_eligible = prediction_result.get('total_eligible', len(predictions))
    
    # Count by category (ML returns Safe, Moderate, Reach; PDF shows Safe/Moderate/Ambitious)
    safe_count = len([p for p in predictions if p.get('category') == 'Safe'])
    moderate_count = len([p for p in predictions if p.get('category') == 'Moderate'])
    ambitious_count = len([p for p in predictions if p.get('category') in ('Ambitious', 'Reach')])
    
    pdf.add_key_value('Total Eligible Colleges', total_eligible)
    pdf.add_key_value('Safe Options (>80%)', safe_count)
    pdf.add_key_value('Moderate Options (50-80%)', moderate_count)
    pdf.add_key_value('Ambitious Options (<50%)', ambitious_count)
    pdf.ln(5)
    
    # ===== RECOMMENDED COLLEGES TABLE =====
    pdf.add_section_title('Top College Recommendations', '')
    
    # Table header
    pdf.set_fill_color(16, 163, 127)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 9)
    
    col_widths = [8, 60, 25, 25, 25, 25, 22]
    headers = ['#', 'College Name', 'Branch', 'Location', 'Cutoff', 'Fee (Rs)', 'Chance']
    
    for i, header in enumerate(headers):
        pdf.cell(col_widths[i], 8, header, border=1, align='C', fill=True)
    pdf.ln()
    
    # Table rows
    pdf.set_font('Helvetica', '', 8)
    pdf.set_text_color(0, 0, 0)
    
    for idx, pred in enumerate(predictions[:15], 1):  # Top 15
        # Alternate row colors
        if idx % 2 == 0:
            pdf.set_fill_color(245, 245, 245)
        else:
            pdf.set_fill_color(255, 255, 255)
            
        # Truncate long college names
        college_name = pred.get('college_name', '')[:30]
        if len(pred.get('college_name', '')) > 30:
            college_name += '...'
            
        fee_val = pred.get('annual_fee', 0)
        fee_str = f"{fee_val:,}" if isinstance(fee_val, (int, float)) else str(fee_val)
        prob_val = pred.get('probability', 0)
        prob_str = f"{prob_val:.0f}%" if isinstance(prob_val, (int, float)) else str(prob_val)
        row_data = [
            str(idx),
            college_name,
            pred.get('branch', 'N/A'),
            (pred.get('location') or 'N/A')[:12],
            str(pred.get('cutoff_rank', 'N/A')),
            fee_str,
            prob_str
        ]
        
        for i, data in enumerate(row_data):
            pdf.cell(col_widths[i], 7, data, border=1, align='C', fill=True)
        pdf.ln()
    
    pdf.ln(10)
    
    # ===== COUNSELLING GUIDANCE =====
    guidance = prediction_result.get('counselling_guidance', {})
    if guidance:
        pdf.add_section_title('Counselling Guidance', '')
        
        if guidance.get('rank_analysis'):
            pdf.add_subsection('Rank Analysis')
            pdf.add_text(guidance['rank_analysis'])
            
        if guidance.get('strategy'):
            pdf.add_subsection('Recommended Strategy')
            pdf.add_text(guidance['strategy'])
    
    # ===== OPTION ENTRY SEQUENCE =====
    option_sequence = prediction_result.get('option_entry_sequence', prediction_result.get('option_sequence', []))
    if option_sequence:
        pdf.add_page()
        pdf.add_section_title('Recommended Option Entry Sequence', '')
        
        pdf.add_text('List your options in this order during KEA counselling:')
        pdf.ln(3)
        
        pdf.set_font('Helvetica', '', 9)
        for i, option in enumerate(option_sequence[:20], 1):
            category_label = option.get('category', '')
            if category_label == 'Safe':
                pdf.set_text_color(34, 139, 34)  # Green
            elif category_label == 'Moderate':
                pdf.set_text_color(255, 165, 0)  # Orange
            else:
                pdf.set_text_color(220, 20, 60)  # Red
                
            pdf.cell(10, 6, f'{i}.', align='R')
            pdf.set_text_color(0, 0, 0)
            college_display = option.get('college_name') or option.get('college', '')
            pdf.cell(0, 6, f" {college_display} - {option.get('branch', '')} ({category_label})", ln=True)
    
    # ===== IMPORTANT NOTES =====
    pdf.ln(10)
    pdf.add_section_title('Important Notes', '')
    
    notes = [
        "1. Cutoff ranks are based on previous year data and may vary.",
        "2. Verify fee structure directly with colleges before admission.",
        "3. Keep checking KEA official website for latest updates.",
        "4. Prepare all required documents before counselling rounds.",
        "5. This is AI-generated guidance. Final decisions should consider multiple factors."
    ]
    
    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(80, 80, 80)
    for note in notes:
        pdf.multi_cell(0, 5, note)
        pdf.ln(1)
    
    # Return PDF as bytes
    return bytes(pdf.output())


def generate_simple_report(student_info: dict, colleges: list) -> bytes:
    """
    Generate a simple report without full prediction result.
    
    Args:
        student_info: Basic student details
        colleges: List of recommended colleges
        
    Returns:
        PDF content as bytes
    """
    # Convert to prediction result format
    prediction_result = {
        'predictions': colleges,
        'total_eligible': len(colleges)
    }
    
    return generate_college_report(prediction_result, student_info)


# Test the generator
if __name__ == "__main__":
    # Sample data for testing
    test_profile = {
        'kcet_rank': 5000,
        'category': 'GM',
        'preferred_branches': ['CSE', 'ECE', 'ISE'],
        'preferred_locations': ['Bangalore', 'Mysore']
    }
    
    test_result = {
        'predictions': [
            {
                'college_name': 'RV College of Engineering',
                'branch': 'CSE',
                'location': 'Bangalore',
                'cutoff_rank': 800,
                'annual_fee': 185000,
                'probability': 25,
                'category': 'Ambitious'
            },
            {
                'college_name': 'BMS College of Engineering',
                'branch': 'CSE',
                'location': 'Bangalore',
                'cutoff_rank': 1200,
                'annual_fee': 165000,
                'probability': 35,
                'category': 'Ambitious'
            },
            {
                'college_name': 'MS Ramaiah Institute of Technology',
                'branch': 'ECE',
                'location': 'Bangalore',
                'cutoff_rank': 4500,
                'annual_fee': 175000,
                'probability': 75,
                'category': 'Moderate'
            },
            {
                'college_name': 'PES University',
                'branch': 'CSE',
                'location': 'Bangalore',
                'cutoff_rank': 3000,
                'annual_fee': 350000,
                'probability': 60,
                'category': 'Moderate'
            },
            {
                'college_name': 'Dr. Ambedkar Institute of Technology',
                'branch': 'CSE',
                'location': 'Bangalore',
                'cutoff_rank': 10000,
                'annual_fee': 95000,
                'probability': 95,
                'category': 'Safe'
            },
        ],
        'total_eligible': 40,
        'counselling_guidance': {
            'rank_analysis': 'With rank 5000, you have a competitive position for mid-tier private colleges and some newer government institutions.',
            'strategy': 'Focus on maximizing options in Round 1. List safe colleges first, then moderate, and ambitious as backup.'
        },
        'option_sequence': [
            {'college_name': 'Dr. Ambedkar IT', 'branch': 'CSE', 'category': 'Safe'},
            {'college_name': 'CMR IT', 'branch': 'CSE', 'category': 'Safe'},
            {'college_name': 'MS Ramaiah', 'branch': 'ECE', 'category': 'Moderate'},
            {'college_name': 'PES University', 'branch': 'CSE', 'category': 'Moderate'},
            {'college_name': 'BMS College', 'branch': 'CSE', 'category': 'Ambitious'},
        ]
    }
    
    # Generate PDF
    pdf_bytes = generate_college_report(test_result, test_profile)
    
    # Save to file for testing
    with open('test_report.pdf', 'wb') as f:
        f.write(pdf_bytes)
    
    print(f"âœ… Test report generated: test_report.pdf ({len(pdf_bytes)} bytes)")

